# Generated by Django 4.2.7 on 2023-11-20 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('matches', '0005_matchresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='countries.country'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='countries.country'),
        ),
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(choices=[('Chinnaswamy', 'Chinnaswamy'), ('Mohali', 'Mohali'), ('Narendra-modi', 'Narendra-modi'), ('mumbai-Wankhede', 'mumbai-Wankhade'), ('Chennai-chepauk', 'Chennai-Chepauk'), ('Kolkata-Eden-gardens', 'Kolkata-Eden-gardens')], max_length=255, null=True),
        ),
    ]
