# Generated by Django 4.2.7 on 2023-11-21 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_country'),
        ('matches', '0007_alter_match_team1_alter_match_team2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchresult',
            name='team',
        ),
        migrations.AddField(
            model_name='matchresult',
            name='team1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_result_team1', to='teams.team'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_result_team2', to='teams.team'),
        ),
    ]
