# Generated by Django 4.2.7 on 2023-11-21 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('teams', '0002_team_user_alter_team_captain_name_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.country'),
        ),
    ]
