# Generated by Django 4.2.7 on 2023-11-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='points',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
