# Generated by Django 4.2.7 on 2023-11-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_alter_leaderboardentry_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboardentry',
            options={'ordering': ['-points']},
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['points'], name='leaderboard_points_f89b96_idx'),
        ),
    ]
