# Generated by Django 4.2.7 on 2023-11-20 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_alter_match_team1_alter_match_team2_and_more'),
        ('countries', '0001_initial'),
        ('players', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='batting_style',
            field=models.CharField(blank=True, choices=[('Right-hand batsmen', 'Right-hand batsmen'), ('Left-hand batsmen', 'Left-hand batsmen')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='bowling_style',
            field=models.CharField(blank=True, choices=[('Right-arm fast', 'Right-arm fast'), ('Left-arm fast', 'Left-arm fast'), ('Left-arm medium', 'Left-arm medium'), ('Right-arm medium', 'Right-arm medium'), ('Left-arm spin', 'Left-arm spin'), ('Right-arm spin', 'Right-arm spin')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.country'),
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='player',
            name='is_captain',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='player_type',
            field=models.CharField(blank=True, choices=[('Batsmen', 'Batsmen'), ('Bowler', 'Bowler'), ('All-rounder', 'All-rounder'), ('Batsmen-Wicketkeeper', 'Batsmen-Wicketkeeper')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PlayerMatchPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.country')),
            ],
        ),
    ]
